# Generated by Django 5.2.1 on 2025-05-20 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='categoria',
            field=models.CharField(choices=[('montaje', 'Montaje'), ('sujetacion', 'Sujetacion'), ('electricas portatiles', 'Electricas Portatiles'), ('electricas estacionarias', 'Electricas Estacionarias'), ('manuales', 'Manuales'), ('corte', 'Corte'), ('medicion', 'Medicion'), ('jardineria', 'Jardineria'), ('carpinteria', 'Carpinteria')], default='otros', max_length=50),
        ),
    ]
