# Generated by Django 5.2.1 on 2025-05-20 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_alter_producto_categoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleado',
            name='rut',
            field=models.CharField(blank=True, max_length=12, null=True, unique=True),
        ),
    ]
