# Generated by Django 5.2.1 on 2025-05-20 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_empleado_rut'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleado',
            name='rut',
            field=models.CharField(max_length=12, unique=True),
        ),
    ]
