# Generated by Django 5.2.1 on 2025-05-22 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_cliente_user_empleado_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleado',
            name='must_change_password',
            field=models.BooleanField(default=True),
        ),
    ]
