# Generated by Django 5.2.1 on 2025-05-23 23:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0012_orden_ordenitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empleado',
            name='email',
        ),
    ]
