# Generated by Django 5.2.1 on 2025-05-24 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0014_alter_cliente_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orden',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('pagada', 'Pagada'), ('fallida', 'Fallida')], default='pendiente', max_length=50),
        ),
    ]
