# Generated by Django 5.2.1 on 2025-05-24 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0015_alter_orden_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordenitem',
            name='cantidad',
            field=models.IntegerField(),
        ),
    ]
